import localFont from 'next/font/local';
import './globals.css';

// Self-hosted Caveat — used for the chalk-on-blackboard level cards.
// Using next/font/local means the @font-face URL is generated by
// Next.js and respects the basePath config when deployed under a
// sub-directory like /Marketing.
const caveat = localFont({
  src: '../../public/fonts/caveat.woff2',
  weight: '500',
  style: 'normal',
  display: 'swap',
  variable: '--font-caveat',
});

export const metadata = {
  title: 'YCYW Advanced Pathways Academy — Programmes for Marketing',
  description: 'Programme catalogue, recap videos, photos, articles, and resources for the marketing team.',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={caveat.variable}>
      <body>{children}</body>
    </html>
  );
}
